# Generated by Django 4.0 on 2021-12-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='detecompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
